name: "Deployment Tailchat Github App"

on:
  push:
    branches:
      - master
    paths:
      - "apps/github-app/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v1
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@master
      env:
        VERSION: ${{ env.GITHUB_SHA }}
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.ORG_ID}}
        vercel-project-id: prj_KwCzbuSaEj3XmP0sYvvnqqiK7nCW
        working-directory: ./apps/github-app
        vercel-args: '--prod'
